### ISSUE TITLE
Manhattan plot

### ISSUE THREAD

**Issue by swvanderlaan** [andreyshabalin/ramwas#1]
Hi,

Just a question regarding the prepare-function for manhattans. It appears that the order of the chromosomes is changed, if the chromosomes are of the character class (_e.g._ 1, 10, 2, 3, 9, X).

I think it happens in the first part of that function:

```
if (is.double(chr)) 
      chr = as.integer(chr)
    if (is.character(chr)) 
      chr = factor(chr)
    if (is.integer(chr)) {
      levels(chr) = as.character(seq_len(tail(chr, 1)))
      class(chr) = "factor"
    }
    poslist = split(pos, chr, drop = FALSE) 

```

Because the function split uses the second argument, which are of class factor. Obviously I want the order of chromosomes to be 1, 2, 3, 9, 10, X. Can you give some pointers as to where to change it in the function to work?

Best,

Sander

**Comment by andreyshabalin** [comment]
Hi Sander,

Thank you for reporting this problem.
I believe I fixed it now with the last commit bb1ad2c74ed311322b4b137b94e3618879c710f6.

Please give it a try and close this issue if it works correctly now.
