### ISSUE TITLE
problem running ramwas2collectqc(param)

### ISSUE THREAD

**Issue by Dagsbio** [andreyshabalin/ramwas#2]
Hi, I am getting this error when running ramwas2collectqc:

![image](https://user-images.githubusercontent.com/23311037/117015244-cd83e100-acf1-11eb-9c3b-a2b8083a523c.png)

Besides, I can't run this line on the vignette: 

![image](https://user-images.githubusercontent.com/23311037/117015340-e9878280-acf1-11eb-986e-dd63b90abd05.png)

Any ideas?

Thank you!

**Comment by Dagsbio** [comment]
Just in case, a bit more info on what I have run: 

![image](https://user-images.githubusercontent.com/23311037/117015557-2489b600-acf2-11eb-8365-fea0a195ee1a.png)

**Comment by Dagsbio** [comment]
Also, forgot to mention I am dealing more specifically with MBD-Seq data here. Thank you!

**Comment by andreyshabalin** [comment]
Hi David,

It's hard to diagnose anything from just the screenshots.

Would you be willing to share your data and scripts?
Then I can take a look and we can then go through all the steps together via zoom.

Andrey

**Comment by andreyshabalin** [comment]
And my apologies for the delayed response.

**Comment by Dagsbio** [comment]
Hi Andrey, that would be fantastic!!

I have got a total of 19 bam samples (averaging 12GB each one) from 4 different cell lines. How do you think is the best way to send them to you? Maybe is a good idea to send you just one of the cell lines (5 samples) and also subsampling those bam files to their 10% percent as described in the top rated answer here? https://bioinformatics.stackexchange.com/questions/402/how-can-i-downsample-a-bam-file-while-keeping-both-reads-in-pairs/5648

**Comment by andreyshabalin** [comment]
Hi David,

I'd prefer to deal with the whole data set.
I am comfortable anything standard for file transfer, like Box.com or Google Drive.

Alternatively, we could use p2p file transfer (Resilio Sync, free version).
I've used Resilio Sync to sync my files between computers and it worked great so far.

Let's continue communications via e-mail: andrey.shabalin@gmail.com

Andrey
