### ISSUE TITLE
How to obtain actual positions of all CpG sites in bam files?

### ISSUE THREAD

**Issue by kaanokay** [andreyshabalin/ramwas#5]
Hi,

I am interested in your package because I want to find actual positions of all CpG sites in bam files. Can I do that by using this package?
If its possible to do, could you help me?

Kind regards.

**Comment by andreyshabalin** [comment]
Hi @kaanokay,

The positions of all CpGs are determined from the reference genome, not the BAM files.
Please see the prepared sets of CpGs and the code for constructing new ones at
https://bioconductor.org/packages/release/bioc/vignettes/ramwas/inst/doc/RW2_CpG_sets.html

Andrey

**Comment by kaanokay** [comment]
Hi @andreyshabalin,

Thank you for the explanation. I'll look into it.

Bw.
